[build]
  args_bin = []
  bin = "./tmp/test/auth/main" # Output executable for the auth test
  cmd = "go build -o ./tmp/test/auth/main ./test/auth/main.go" # Build the auth test
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # include_dir = ["."] # Watch for changes in the test directory
  include_ext = ["go", "tpl", "tmpl", "html"]
  # include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
