// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `db:"id" json:"id"`
	AccountID             string           `db:"account_id" json:"account_id"`
	ProviderID            string           `db:"provider_id" json:"provider_id"`
	UserID                string           `db:"user_id" json:"user_id"`
	AccessToken           pgtype.Text      `db:"access_token" json:"access_token"`
	RefreshToken          pgtype.Text      `db:"refresh_token" json:"refresh_token"`
	IDToken               pgtype.Text      `db:"id_token" json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `db:"access_token_expires_at" json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `db:"refresh_token_expires_at" json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `db:"scope" json:"scope"`
	Password              pgtype.Text      `db:"password" json:"password"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Author struct {
	ID   int32       `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Bio  pgtype.Text `db:"bio" json:"bio"`
}

type Session struct {
	ID        string           `db:"id" json:"id"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	Token     string           `db:"token" json:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IpAddress pgtype.Text      `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text      `db:"user_agent" json:"user_agent"`
	UserID    string           `db:"user_id" json:"user_id"`
}

type User struct {
	ID            string           `db:"id" json:"id"`
	Name          string           `db:"name" json:"name"`
	Email         string           `db:"email" json:"email"`
	EmailVerified bool             `db:"email_verified" json:"email_verified"`
	Image         pgtype.Text      `db:"image" json:"image"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Verification struct {
	ID         string           `db:"id" json:"id"`
	Identifier string           `db:"identifier" json:"identifier"`
	Value      string           `db:"value" json:"value"`
	ExpiresAt  pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
